name: Create Release on Dependabot Update

permissions: write-all

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  create_release:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - name: Check if the PR is from Dependabot
        id: dependabot_check
        run: echo "::set-output name=is_dependabot::${{ contains(github.actor, 'dependabot') }}"

      - name: Enable auto-merge for Dependabot PRs
        if: steps.dependabot_check.outputs.is_dependabot == 'true' && github.event_name == 'pull_request'
        run: gh pr merge --auto --merge "$PR_URL" # Use Github CLI to merge automatically the PR
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              
      - name: Checkout repository AFTER MERGE
        uses: actions/checkout@v2

      - name: Get latest release version
        id: get_latest_release
        run: |
          latest_release=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest | jq -r '.tag_name')
          echo "::set-output name=version::$latest_release"

      - name: Calculate next patch level version
        id: calculate_patch_level
        run: |
          IFS='.' read -r -a version_parts <<< "${{ steps.get_latest_release.outputs.version }}"
          next_patch_level=$((version_parts[2]+1))
          next_version="${version_parts[0]}.${version_parts[1]}.$next_patch_level"
          echo "::set-output name=next_version::$next_version"

      - name: Create Release
        if: steps.dependabot_check.outputs.is_dependabot == 'true' && github.event_name == 'pull_request'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.calculate_patch_level.outputs.next_version }}
          release_name: render-guides Sync release ${{ steps.calculate_patch_level.outputs.next_version }}
          body: Automated synchronization with the main render-guides docker container.
          draft: false
          prerelease: false
